name: Salesforce Code Analyzer Workflow(Standard Rules) - Added/Modified files
on: [pull_request]
jobs:
  salesforce-code-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4
      - name: Get modified files
        id: files
        continue-on-error: true
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"
      - name: Prepare files for code scanner
        run: |
          echo "Creating directory scanner_files"  
          mkdir scanner_files
          IFS=',' read -ra added_modified_files_split <<< "${{ steps.files.outputs.added_modified }}"
          for addedModifiedFile in "${added_modified_files_split[@]}"; do
              cp "$addedModifiedFile" scanner_files
          done

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --engine pmd,eslint-lwc --normalize-severity --target scanner_files --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results

      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
